<?php

namespace App;



use Illuminate\Database\Eloquent\SoftDeletes;

use Illuminate\Database\Eloquent\Model;



/**

 * Class Vendor

 *

 * @package App

 * @property string $first_name

 * @property string $last_name

 * @property string $company_name

 * @property string $email

 * @property string $phone

 * @property string $website

 * @property string $skype

 * @property string $country

 * @property string $client_status

*/

class Mmrmanpowerreport extends Model

{
  
    use SoftDeletes;
	
   protected $fillable = ['site','year','month','mmr_agm_hr_shared',
  'mmr_agm_hr_full',
  'mmr_agm_hr_ch',
  'mmr_assistant_shared',
  'mmr_assistant_full',
  'mmr_assistant_ch',
  'mmr_asst_help_desk_shared',
  'mmr_asst_help_desk_full',
  'mmr_asst_help_desk_ch',
  'mmr_asst_sec_officer_shared',
  'mmr_asst_sec_officer_full',
  'mmr_asst_sec_officer_ch',
  'mmr_asst_stores_shared',
  'mmr_asst_stores_full',
  'mmr_asst_stores_ch',
  'mmr_asst_eng_facility_shared',
  'mmr_asst_eng_facility_full',
  'mmr_asst_eng_facility_ch',
  'mmr_asst_mngr_pms_shared',
  'mmr_asst_mngr_pms_full',
  'mmr_asst_mngr_pms_ch',
  'mmr_asst_mngr_security_shared',
  'mmr_asst_mngr_security_full',
  'mmr_asst_mngr_security_ch',
  'mmr_bms_operator_shared',
  'mmr_bms_operator_full',
  'mmr_bms_operator_ch',
  'mmr_care_taker_ch_shared',
  'mmr_care_taker_ch_full',
  'mmr_care_taker_ch_ch',
  'mmr_carpenter_shared',
  'mmr_carpenter_full',
  'mmr_carpenter_ch',
  'mmr_attendant_shared',
  'mmr_attendant_full',
  'mmr_attendant_ch',
  'mmr_dgm_facility_shared',
  'mmr_dgm_facility_full',
  'mmr_dgm_facility_ch',
  'mmr_dgm_bd_operations_shared',
  'mmr_dgm_bd_operations_full',
  'mmr_dgm_bd_operations_ch',
  'mmr_drivers_shared',
  'mmr_drivers_full',
  'mmr_drivers_ch',
  'mmr_dy_manger_pms_shared',
  'mmr_dy_manger_pms_full',
  'mmr_dy_manger_pms_ch',
  'mmr_dy_mang_facility_shared',
  'mmr_dy_mang_facility_full',
  'mmr_dy_mang_facility_ch',
  'mmr_electrician_shared',
  'mmr_electrician_full',
  'mmr_electrician_ch',
  'mmr_eng_facility_shared',
  'mmr_eng_facility_full',
  'mmr_eng_facility_ch',
  'mmr_executive_ch_shared',
  'mmr_executive_ch_full',
  'mmr_executive_ch_ch',
  'mmr_exec_hr_shared',
  'mmr_exec_hr_full',
  'mmr_exec_hr_ch',
  'mmr_exec_pms_shared',
  'mmr_exec_pms_full',
  'mmr_exec_pms_ch',
  'mmr_front_office_exec_shared',
  'mmr_front_office_exec_full',
  'mmr_front_office_exec_ch',
  'mmr_garden_help_shared',
  'mmr_garden_help_full',
  'mmr_garden_help_ch',
  'mmr_gardener_shared',
  'mmr_gardener_full',
  'mmr_gardener_ch',
  'mmr_gas_technician_shared',
  'mmr_gas_technician_full',
  'mmr_gas_technician_ch',
  'mmr_general_manager_hr_shared',
  'mmr_general_manager_hr_full',
  'mmr_general_manager_hr_ch',
  'mmr_get_shared',
  'mmr_get_full',
  'mmr_get_ch',
  'mmr_gymboy_shared',
  'mmr_gymboy_full',
  'mmr_gymboy_ch',
  'mmr_gym_trainer_shared',
  'mmr_gym_trainer_full',
  'mmr_gym_trainer_ch',
  'mmr_head_guard_security_shared',
  'mmr_head_guard_security_full',
  'mmr_head_guard_security_ch',
  'mmr_helper_shared',
  'mmr_helper_full',
  'mmr_helper_ch',
  'mmr_house_keeper_shared',
  'mmr_house_keeper_full',
  'mmr_house_keeper_ch',
  'mmr_hvac_technician_shared',
  'mmr_hvac_technician_full',
  'mmr_hvac_technician_ch',
  'mmr_jr_officer_horticulture_shared',
  'mmr_jr_officer_horticulture_full',
  'mmr_jr_officer_horticulture_ch',
  'mmr_jr_executive_shared',
  'mmr_jr_executive_full',
  'mmr_jr_executive_ch',
  'mmr_jr_executive_accounts_shared',
  'mmr_jr_executive_accounts_full',
  'mmr_jr_executive_accounts_ch',
  'mmr_jr_executive_ch_shared',
  'mmr_jr_executive_ch_full',
  'mmr_jr_executive_ch_ch',
  'mmr_jr_officer_fs_shared',
  'mmr_jr_officer_fs_full',
  'mmr_jr_officer_fs_ch',
  'mmr_jr_officer_facilities_shared',
  'mmr_jr_officer_facilities_full',
  'mmr_jr_officer_facilities_ch',
  'mmr_jr_supervisor_security_shared',
  'mmr_jr_supervisor_security_full',
  'mmr_jr_supervisor_security_ch',
  'mmr_jr_executive_admin_shared',
  'mmr_jr_executive_admin_full',
  'mmr_jr_executive_admin_ch',
  'mmr_jr_executive_pms_shared',
  'mmr_jr_executive_pms_full',
  'mmr_jr_executive_pms_ch',
  'mmr_jr_officer_pms_shared',
  'mmr_jr_officer_pms_full',
  'mmr_jr_officer_pms_ch',
  'mmr_lady_security_gaurd_shared',
  'mmr_lady_security_gaurd_full',
  'mmr_lady_security_gaurd_ch',
  'mmr_lift_care_taker_shared',
  'mmr_lift_care_taker_full',
  'mmr_lift_care_taker_ch',
  'mmr_manager_facilities_shared',
  'mmr_manager_facilities_full',
  'mmr_manager_facilities_ch',
  'mmr_manager_firesafety_shared',
  'mmr_manager_firesafety_full',
  'mmr_manager_firesafety_ch',
  'mmr_manager_horticulture_shared',
  'mmr_manager_horticulture_full',
  'mmr_manager_horticulture_ch',
  'mmr_manager_hr_shared',
  'mmr_manager_hr_full',
  'mmr_manager_hr_ch',
  'mmr_manager_operations_shared',
  'mmr_manager_operations_full',
  'mmr_manager_operations_ch',
  'mmr_manager_td_shared',
  'mmr_manager_td_full',
  'mmr_manager_td_ch',
  'mmr_mason_shared',
  'mmr_mason_full',
  'mmr_mason_ch',
  'mmr_mechanic_shared',
  'mmr_mechanic_full',
  'mmr_mechanic_ch',
  'mmr_multi_suill_technician_shared',
  'mmr_multi_suill_technician_full',
  'mmr_multi_suill_technician_ch',
  'mmr_multi_technician_shared',
  'mmr_multi_technician_full',
  'mmr_multi_technician_ch',
  'mmr_office_assistant_shared',
  'mmr_office_assistant_full',
  'mmr_office_assistant_ch',
  'mmr_office_attendant_shared',
  'mmr_office_attendant_full',
  'mmr_office_attendant_ch',
  'mmr_office_boy_shared',
  'mmr_office_boy_full',
  'mmr_office_boy_ch',
  'mmr_officer_shared',
  'mmr_officer_full',
  'mmr_officer_ch',
  'mmr_officer_security_shared',
  'mmr_officer_security_full',
  'mmr_officer_security_ch',
  'mmr_officer_training_shared',
  'mmr_officer_training_full',
  'mmr_officer_training_ch',
  'mmr_operator_ros_machine_shared',
  'mmr_operator_ros_machine_full',
  'mmr_operator_ros_machine_ch',
  'mmr_operator_stp_shared',
  'mmr_operator_stp_full',
  'mmr_operator_stp_ch',
  'mmr_painter_shared',
  'mmr_painter_full',
  'mmr_painter_ch',
  'mmr_plumber_shared',
  'mmr_plumber_full',
  'mmr_plumber_ch',
  'mmr_safety_steward_shared',
  'mmr_safety_steward_full',
  'mmr_safety_steward_ch',
  'mmr_security_guard_shared',
  'mmr_security_guard_full',
  'mmr_security_guard_ch',
  'mmr_security_supervisor_shared',
  'mmr_security_supervisor_full',
  'mmr_security_supervisor_ch',
  'mmr_sr_carpenter_shared',
  'mmr_sr_carpenter_full',
  'mmr_sr_carpenter_ch',
  'mmr_sr_exe_horticulture_shared',
  'mmr_sr_exe_horticulture_full',
  'mmr_sr_exe_horticulture_ch',
  'mmr_sr_engineer_facilities_shared',
  'mmr_sr_engineer_facilities_full',
  'mmr_sr_engineer_facilities_ch',
  'mmr_sr_executive_accounts_shared',
  'mmr_sr_executive_accounts_full',
  'mmr_sr_executive_accounts_ch',
  'mmr_sr_executive_pms_shared',
  'mmr_sr_executive_pms_full',
  'mmr_sr_executive_pms_ch',
  'mmr_sr_lady_sup_security_shared',
  'mmr_sr_lady_sup_security_full',
  'mmr_sr_lady_sup_security_ch',
  'mmr_sr_manager_facilities_shared',
  'mmr_sr_manager_facilities_full',
  'mmr_sr_manager_facilities_ch',
  'mmr_sr_officer_safety_shared',
  'mmr_sr_officer_safety_full',
  'mmr_sr_officer_safety_ch',
  'mmr_sr_officer_stores_shared',
  'mmr_sr_officer_stores_full',
  'mmr_sr_officer_stores_ch',
  'mmr_sr_supervisor_shared',
  'mmr_sr_supervisor_full',
  'mmr_sr_supervisor_ch',
  'mmr_sr_supervisor_hk_shared',
  'mmr_sr_supervisor_hk_full',
  'mmr_sr_supervisor_hk_ch',
  'mmr_sr_supervisor_plumbing_shared',
  'mmr_sr_supervisor_plumbing_full',
  'mmr_sr_supervisor_plumbing_ch',
  'mmr_sr_supervisor_security_shared',
  'mmr_sr_supervisor_security_full',
  'mmr_sr_supervisor_security_ch',
  'mmr_sr_technician_shared',
  'mmr_sr_technician_full',
  'mmr_sr_technician_ch',
  'mmr_srasst_help_desk_shared',
  'mmr_srasst_help_desk_full',
  'mmr_srasst_help_desk_ch',
  'mmr_sr_executive_reso_train_shared',
  'mmr_sr_executive_reso_train_full',
  'mmr_sr_executive_reso_train_ch',
  'mmr_sr_manager_shared',
  'mmr_sr_manager_full',
  'mmr_sr_manager_ch',
  'mmr_sr_office_assistant_shared',
  'mmr_sr_office_assistant_full',
  'mmr_sr_office_assistant_ch',
  'mmr_sr_officer_irrigation_shared',
  'mmr_sr_officer_irrigation_full',
  'mmr_sr_officer_irrigation_ch',
  'mmr_sr_officer_sec_train_shared',
  'mmr_sr_officer_sec_train_full',
  'mmr_sr_officer_sec_train_ch',
  'mmr_sr_officer_horticulture_shared',
  'mmr_sr_officer_horticulture_full',
  'mmr_sr_officer_horticulture_ch',
  'mmr_sr_officer_security_shared',
  'mmr_sr_officer_security_full',
  'mmr_sr_officer_security_ch',
  'mmr_sr_plumber_shared',
  'mmr_sr_plumber_full',
  'mmr_sr_plumber_ch',
  'mmr_sr_supervisor_pms_shared',
  'mmr_sr_supervisor_pms_full',
  'mmr_sr_supervisor_pms_ch',
  'mmr_sr_supervisor_tech_shared',
  'mmr_sr_supervisor_tech_full',
  'mmr_sr_supervisor_tech_ch',
  'mmr_steward_fire_safety_shared',
  'mmr_steward_fire_safety_full',
  'mmr_steward_fire_safety_ch',
  'mmr_supervisor_shared',
  'mmr_supervisor_full',
  'mmr_supervisor_ch',
  'mmr_supervisor_facilities_shared',
  'mmr_supervisor_facilities_full',
  'mmr_supervisor_facilities_ch',
  'mmr_supervisor_firesafety_shared',
  'mmr_supervisor_firesafety_full',
  'mmr_supervisor_firesafety_ch',
  'mmr_supervisor_gardening_shared',
  'mmr_supervisor_gardening_full',
  'mmr_supervisor_gardening_ch',
  'mmr_supervisor_hk_shared',
  'mmr_supervisor_hk_full',
  'mmr_supervisor_hk_ch',
  'mmr_supervisor_maintenance_shared',
  'mmr_supervisor_maintenance_full',
  'mmr_supervisor_maintenance_ch',
  'mmr_supervisor_plumbing_shared',
  'mmr_supervisor_plumbing_full',
  'mmr_supervisor_plumbing_ch',
  'mmr_supervisor_security_shared',
  'mmr_supervisor_security_full',
  'mmr_supervisor_security_ch',
  'mmr_supervisor_technical_shared',
  'mmr_supervisor_technical_full',
  'mmr_supervisor_technical_ch',
  'mmr_supervisor_clubhouse_shared',
  'mmr_supervisor_clubhouse_full',
  'mmr_supervisor_clubhouse_ch',
  'mmr_supervisor_horticulture_shared',
  'mmr_supervisor_horticulture_full',
  'mmr_supervisor_horticulture_ch',
  'mmr_supervisor_stp_shared',
  'mmr_supervisor_stp_full',
  'mmr_supervisor_stp_ch',
  'mmr_swimming_coach_shared',
  'mmr_swimming_coach_full',
  'mmr_swimming_coach_ch',
  'mmr_swimming_pool_operator_shared',
  'mmr_swimming_pool_operator_full',
  'mmr_swimming_pool_operator_ch',
  'mmr_swimming_pool_tech_shared',
  'mmr_swimming_pool_tech_full',
  'mmr_swimming_pool_tech_ch',
  'mmr_technician_shared',
  'mmr_technician_full',
  'mmr_technician_ch',
  'mmr_tennis_coach_shared',
  'mmr_tennis_coach_full',
  'mmr_tennis_coach_ch',
  'mmr_tr_mst_shared',
  'mmr_tr_mst_full',
  'mmr_tr_mst_ch',
  'mmr_tr_sup_fire_safety_shared',
  'mmr_tr_sup_fire_safety_full',
  'mmr_tr_sup_fire_safety_ch',
  'mmr_tr_assistant_stores_shared',
  'mmr_tr_assistant_stores_full',
  'mmr_tr_assistant_stores_ch',
  'mmr_tractor_driver_shared',
  'mmr_tractor_driver_full',
  'mmr_tractor_driver_ch',
  'mmr_vp_operations_shared',
  'mmr_vp_operations_full',
  'mmr_vp_operations_ch',
  'mmr_welder_shared',
  'mmr_welder_full',
  'mmr_welder_ch',
  'mmr_incharge_facilities_shared',
  'mmr_incharge_facilities_full',
  'mmr_incharge_facilities_ch',
  'mmr_incharge_fms_shared',
  'mmr_incharge_fms_full',
  'mmr_incharge_fms_ch',
  'mmr_incharge_pms_shared',
  'mmr_incharge_pms_full',
  'mmr_incharge_pms_ch'
];

   
    public static function boot()

    {

        parent::boot();

        Mmrmanpowerreport::observe(new \App\Observers\UserActionsObserver);

    }

    

}

